[package]
authors    =["{{authors}}"]
description="""{{description}}"""
edition    ="2021"
license    ="Apache2.0 OR MIT"
name       ="{{project-name}}"
repository ="https://github.com/thor314/{{project-name}}"
version    ="0.1.0"

[dependencies]
anyhow   ="1.0"
thiserror="1.0"
log      ="0.4" 

[dev-dependencies]
criterion = "0.4"
rstest = "0.16"         # testing convenience proc-macros
test-log = "0.2"        # log/tracing independent test-log consumer
# test-log =  { version = "0.2", default-features = false, features = ["trace"] } 

arbitrary = { version = "1.1", features = ["derive"] } # see quickcheck
quickcheck = "1.0"      # lowkey proptest suite
quickcheck_macros = "1" # derive 

[[test]]
name = "integration"
path = "tests/tests.rs"

[[bench]]
name = "bench"
harness = false
