# Rust template: https://github.com/actions/starter-workflows/blob/main/ci/rust.yml
# Resources: https://docs.github.com/en/actions
# Examples: https://github.com/actions/starter-workflows
# Process: make small changes, push them, check the Actions tab on github
# also see templates https://github.com/rust-github/template/tree/main/.github/workflows
name: Rust
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always # pretty colors

jobs:
  check:
    name: Check 
    runs-on: ubuntu-latest
    steps:
      # sets many `with` env defaults. https://github.com/actions/checkout
    - uses: actions/checkout@v3
      # run shell commands. must have `-`.
    - run: bash .github/scripts/check.sh
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: bash .github/scripts/test.sh
  lint:
    name: Lint 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: bash .github/scripts/lint.sh
  fmt:
    name: Fmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: bash .github/scripts/fmt.sh
