[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"
authors = ["{{authors}}"]
repository = "https://github.com/{{gh-username}}/{{project-name}}"
description = """{{description}}"""
license = "Unlicense OR MIT"

[dependencies]
{% if tm == "bin" %}
# Binary
dotenv = "0.15" # .env file parsing
clap = { version = "3.2", features = ["derive"] }
validator = { version = "0.15", features = ["derive"] }
{% endif %}
# Common
cfg-if = { version = "1.0.0" } # branching compilation logic

# Common, but not used in this template. optional => won't be compiled unless used
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
rand = { version = "0.8", optional = true }
cute =  { version ="0.3", optional = true } # python-like list comprehensions
{% if tm == "lib" %}
validator = { version = "0.15", features = ["derive"], optional = true}
{% endif %}
# Error Handling
thiserror = "1.0"
anyhow = "1.0"

# Logging
log = "0.4" 
env_logger = "0.9"

# Rhai scripting
# https://rhai.rs/book/start/features.html
# rhai = { version = "1.8.0", features = [ "sync", "unchecked", "only_i32", "no_float", "no_module", "no_function" ] }

[features]
some_feature = ["dep:serde","dep:serde_json"] # use this to use optional dependencies

[dev-dependencies]
# Bench
criterion = "0.3"
iai = "0.1" # criterion alternative
# Testing utils
rstest = "0.15"
quickcheck = "1.0"
quickcheck_macros = "1" # derive 
arbitrary = { version = "1.1", features = ["derive"] }

[[test]]
name = "integration"
path = "tests/tests.rs"

[[bench]]
name = "bench"
harness = false
